package eu.unifiedviews.plugins.transformer.filesrenamer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.ObjectProperty;
import com.vaadin.data.util.converter.StringToIntegerConverter;
import com.vaadin.data.validator.IntegerRangeValidator;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

import eu.unifiedviews.helpers.dpu.localization.Messages;

/**
 * Renamer GUI component.
 * Generated with Eclipse Vaadin plugin.
 * 
 * @author mva
 */
public class RenamerComponent extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * 
     */
    private static final long serialVersionUID = -7103463309446962661L;

    @AutoGenerated
    private AbsoluteLayout mainLayout;

    @AutoGenerated
    private VerticalLayout verticalLayout_1;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_5;

    @AutoGenerated
    private Panel panel_4;

    @AutoGenerated
    private VerticalLayout verticalLayout_5;

    @AutoGenerated
    private Label label_12;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_4;

    @AutoGenerated
    private Panel panel_5;

    @AutoGenerated
    private VerticalLayout verticalLayout_6;

    @AutoGenerated
    private Table table_3;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private Panel panel_3;

    @AutoGenerated
    private VerticalLayout verticalLayout_4;

    @AutoGenerated
    private GridLayout gridLayout_3;

    @AutoGenerated
    private TextField textField_5;

    @AutoGenerated
    private Label label_11;

    @AutoGenerated
    private TextField textField_4;

    @AutoGenerated
    private Label label_10;

    @AutoGenerated
    private TextField textField_3;

    @AutoGenerated
    private Label label_9;

    @AutoGenerated
    private Panel panel_2;

    @AutoGenerated
    private VerticalLayout verticalLayout_3;

    @AutoGenerated
    private GridLayout gridLayout_2;

    @AutoGenerated
    private Label label_8;

    @AutoGenerated
    private Button button_6;

    @AutoGenerated
    private Label label_7;

    @AutoGenerated
    private Button button_5;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;

    @AutoGenerated
    private TextField textField_2;

    @AutoGenerated
    private Label label_6;

    @AutoGenerated
    private Panel panel_1;

    @AutoGenerated
    private VerticalLayout verticalLayout_2;

    @AutoGenerated
    private GridLayout gridLayout_1;

    @AutoGenerated
    private Label label_5;

    @AutoGenerated
    private Button button_4;

    @AutoGenerated
    private Label label_3;

    @AutoGenerated
    private Button button_2;

    @AutoGenerated
    private Label label_4;

    @AutoGenerated
    private Button button_3;

    @AutoGenerated
    private Label label_2;

    @AutoGenerated
    private Button button_1;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private TextField textField_1;

    @AutoGenerated
    private Label label_1;

    private final ObjectProperty<Integer> counterStart =
            new ObjectProperty<Integer>(0);

    private final ObjectProperty<Integer> counterStep =
            new ObjectProperty<Integer>(1);

    private final ObjectProperty<Integer> counterDigits =
            new ObjectProperty<Integer>(1);

    private Messages messages;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public RenamerComponent(Messages messages) {
        this.messages = messages;
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // set masks default values
        textField_1.setValue("[N]");
        textField_2.setValue("[E]");

        // Use a converter between String and Integer
        textField_3.addValidator(new IntegerRangeValidator(messages.getString("RenamerComponent.value.greaterThen.0"), 0, null));
        textField_3.setConverter(new StringToIntegerConverter());
        textField_3.setPropertyDataSource(counterStart);

        textField_4.addValidator(new IntegerRangeValidator(messages.getString("RenamerComponent.value.greaterThen.1"), 1, null));
        textField_4.setConverter(new StringToIntegerConverter());
        textField_4.setPropertyDataSource(counterStep);

        textField_5.addValidator(new IntegerRangeValidator(messages.getString("RenamerComponent.value.greaterThen.1"), 1, null));
        textField_5.setConverter(new StringToIntegerConverter());
        textField_5.setPropertyDataSource(counterDigits);

        // set table columns
        table_3.addContainerProperty(messages.getString("RenamerComponent.oldName"), String.class, null);
        table_3.addContainerProperty(messages.getString("RenamerComponent.newName"), String.class, null);

        // [N] button
        button_1.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_1.setValue(textField_1.getValue() + "[N]");
            }
        });

        // [C] button
        button_2.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_1.setValue(textField_1.getValue() + "[C]");
            }
        });

        // [D] button
        button_3.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_1.setValue(textField_1.getValue() + "[D]");
            }
        });

        // [T] button
        button_4.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_1.setValue(textField_1.getValue() + "[T]");
            }
        });

        // [E] button
        button_5.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_2.setValue(textField_2.getValue() + "[E]");
            }
        });

        // [C] extension mask button
        button_6.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(final ClickEvent event) {
                textField_2.setValue(textField_2.getValue() + "[C]");
            }
        });

        // set DPU description
        panel_4.setContent(new Label(messages.getString("RenamerComponent.description1")
                + messages.getString("RenamerComponent.description2")
                + messages.getString("RenamerComponent.description3")
                + messages.getString("RenamerComponent.description4"), ContentMode.HTML));
    }

    public RenameConfig_V1 getConfig() {
        RenameConfig_V1 config = new RenameConfig_V1();
        config.setMask(textField_1.getValue());
        config.setExtensionMask(textField_2.getValue());
        config.setCounterStart(counterStart.getValue());
        config.setCounterStep(counterStep.getValue());
        config.setCounterDigits(counterDigits.getValue());
        return config;
    }

    public void setConfig(RenameConfig_V1 config) {
        textField_1.setValue(config.getMask());
        textField_2.setValue(config.getExtensionMask());
        textField_3.setValue(config.getCounterStart().toString());
        textField_4.setValue(config.getCounterStep().toString());
        textField_5.setValue(config.getCounterDigits().toString());
    }

    public Table getTable() {
        return table_3;
    }

    public TextField getMaskTextField() {
        return textField_1;
    }

    public TextField getExtensionMaskTextField() {
        return textField_2;
    }

    public TextField getCounterStartStepper() {
        return textField_3;
    }

    public TextField getCounterStepStepper() {
        return textField_4;
    }

    public TextField getCounterDigitsStepper() {
        return textField_5;
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("600px");

        // top-level component properties
        setWidth("100.0%");
        setHeight("600px");

        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        mainLayout.addComponent(verticalLayout_1, "top:0.0px;right:0.0px;bottom:0.0px;left:0.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("100.0%");
        verticalLayout_1.setHeight("100.0%");
        verticalLayout_1.setMargin(false);

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_1.addComponent(horizontalLayout_1);
        verticalLayout_1.setExpandRatio(horizontalLayout_1, 1.0f);

        // horizontalLayout_4
        horizontalLayout_4 = buildHorizontalLayout_4();
        verticalLayout_1.addComponent(horizontalLayout_4);
        verticalLayout_1.setExpandRatio(horizontalLayout_4, 1.0f);

        // horizontalLayout_5
        horizontalLayout_5 = buildHorizontalLayout_5();
        verticalLayout_1.addComponent(horizontalLayout_5);
        verticalLayout_1.setExpandRatio(horizontalLayout_5, 1.0f);

        return verticalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("700px");
        horizontalLayout_1.setHeight("200px");
        horizontalLayout_1.setMargin(true);
        horizontalLayout_1.setSpacing(true);

        // panel_1
        panel_1 = buildPanel_1();
        horizontalLayout_1.addComponent(panel_1);
        horizontalLayout_1.setExpandRatio(panel_1, 1.0f);

        // panel_2
        panel_2 = buildPanel_2();
        horizontalLayout_1.addComponent(panel_2);
        horizontalLayout_1.setExpandRatio(panel_2, 1.0f);

        // panel_3
        panel_3 = buildPanel_3();
        horizontalLayout_1.addComponent(panel_3);
        horizontalLayout_1.setExpandRatio(panel_3, 1.0f);

        return horizontalLayout_1;
    }

    @AutoGenerated
    private Panel buildPanel_1() {
        // common part: create layout
        panel_1 = new Panel();
        panel_1.setCaption(messages.getString("RenamerComponent.fileName"));
        panel_1.setImmediate(false);
        panel_1.setWidth("100.0%");
        panel_1.setHeight("100.0%");

        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        panel_1.setContent(verticalLayout_2);

        return panel_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(true);
        verticalLayout_2.setSpacing(true);

        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        verticalLayout_2.addComponent(horizontalLayout_2);

        // gridLayout_1
        gridLayout_1 = buildGridLayout_1();
        verticalLayout_2.addComponent(gridLayout_1);
        verticalLayout_2.setExpandRatio(gridLayout_1, 1.0f);

        return verticalLayout_2;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("-1px");
        horizontalLayout_2.setHeight("-1px");
        horizontalLayout_2.setMargin(false);
        horizontalLayout_2.setSpacing(true);

        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("-1px");
        label_1.setHeight("-1px");
        label_1.setValue(messages.getString("RenamerComponent.mask"));
        horizontalLayout_2.addComponent(label_1);

        // textField_1
        textField_1 = new TextField();
        textField_1.setImmediate(false);
        textField_1.setWidth("-1px");
        textField_1.setHeight("-1px");
        horizontalLayout_2.addComponent(textField_1);

        return horizontalLayout_2;
    }

    @AutoGenerated
    private GridLayout buildGridLayout_1() {
        // common part: create layout
        gridLayout_1 = new GridLayout();
        gridLayout_1.setImmediate(false);
        gridLayout_1.setWidth("100.0%");
        gridLayout_1.setHeight("100.0%");
        gridLayout_1.setMargin(false);
        gridLayout_1.setColumns(4);
        gridLayout_1.setRows(2);

        // button_1
        button_1 = new Button();
        button_1.setCaption("[N]");
        button_1.setImmediate(true);
        button_1.setWidth("-1px");
        button_1.setHeight("-1px");
        gridLayout_1.addComponent(button_1, 0, 0);

        // label_2
        label_2 = new Label();
        label_2.setImmediate(false);
        label_2.setWidth("-1px");
        label_2.setHeight("-1px");
        label_2.setValue(messages.getString("RenamerComponent.description.name"));
        gridLayout_1.addComponent(label_2, 1, 0);

        // button_3
        button_3 = new Button();
        button_3.setCaption("[D]");
        button_3.setImmediate(true);
        button_3.setWidth("-1px");
        button_3.setHeight("-1px");
        gridLayout_1.addComponent(button_3, 2, 0);

        // label_4
        label_4 = new Label();
        label_4.setImmediate(false);
        label_4.setWidth("-1px");
        label_4.setHeight("-1px");
        label_4.setValue(messages.getString("RenamerComponent.description.date"));
        gridLayout_1.addComponent(label_4, 3, 0);

        // button_2
        button_2 = new Button();
        button_2.setCaption("[C]");
        button_2.setImmediate(true);
        button_2.setWidth("-1px");
        button_2.setHeight("-1px");
        gridLayout_1.addComponent(button_2, 0, 1);

        // label_3
        label_3 = new Label();
        label_3.setImmediate(false);
        label_3.setWidth("-1px");
        label_3.setHeight("-1px");
        label_3.setValue(messages.getString("RenamerComponent.description.counter"));
        gridLayout_1.addComponent(label_3, 1, 1);

        // button_4
        button_4 = new Button();
        button_4.setCaption("[T]");
        button_4.setImmediate(true);
        button_4.setWidth("-1px");
        button_4.setHeight("-1px");
        gridLayout_1.addComponent(button_4, 2, 1);

        // label_5
        label_5 = new Label();
        label_5.setImmediate(false);
        label_5.setWidth("-1px");
        label_5.setHeight("-1px");
        label_5.setValue(messages.getString("RenamerComponent.description.time"));
        gridLayout_1.addComponent(label_5, 3, 1);

        return gridLayout_1;
    }

    @AutoGenerated
    private Panel buildPanel_2() {
        // common part: create layout
        panel_2 = new Panel();
        panel_2.setCaption(messages.getString("RenamerComponent.extension"));
        panel_2.setImmediate(false);
        panel_2.setWidth("100.0%");
        panel_2.setHeight("100.0%");

        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        panel_2.setContent(verticalLayout_3);

        return panel_2;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(true);
        verticalLayout_3.setSpacing(true);

        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        verticalLayout_3.addComponent(horizontalLayout_3);

        // gridLayout_2
        gridLayout_2 = buildGridLayout_2();
        verticalLayout_3.addComponent(gridLayout_2);
        verticalLayout_3.setExpandRatio(gridLayout_2, 1.0f);

        return verticalLayout_3;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3() {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("-1px");
        horizontalLayout_3.setHeight("-1px");
        horizontalLayout_3.setMargin(false);

        // label_6
        label_6 = new Label();
        label_6.setImmediate(false);
        label_6.setWidth("-1px");
        label_6.setHeight("-1px");
        label_6.setValue(messages.getString("RenamerComponent.extension.mask"));
        horizontalLayout_3.addComponent(label_6);

        // textField_2
        textField_2 = new TextField();
        textField_2.setImmediate(false);
        textField_2.setWidth("-1px");
        textField_2.setHeight("-1px");
        horizontalLayout_3.addComponent(textField_2);

        return horizontalLayout_3;
    }

    @AutoGenerated
    private GridLayout buildGridLayout_2() {
        // common part: create layout
        gridLayout_2 = new GridLayout();
        gridLayout_2.setImmediate(false);
        gridLayout_2.setWidth("100.0%");
        gridLayout_2.setHeight("100.0%");
        gridLayout_2.setMargin(false);
        gridLayout_2.setColumns(2);
        gridLayout_2.setRows(2);

        // button_5
        button_5 = new Button();
        button_5.setCaption("[E]");
        button_5.setImmediate(true);
        button_5.setWidth("-1px");
        button_5.setHeight("-1px");
        gridLayout_2.addComponent(button_5, 0, 0);

        // label_7
        label_7 = new Label();
        label_7.setImmediate(false);
        label_7.setWidth("-1px");
        label_7.setHeight("-1px");
        label_7.setValue(messages.getString("RenamerComponent.extension.description"));
        gridLayout_2.addComponent(label_7, 1, 0);

        // button_6
        button_6 = new Button();
        button_6.setCaption("[C]");
        button_6.setImmediate(true);
        button_6.setWidth("-1px");
        button_6.setHeight("-1px");
        gridLayout_2.addComponent(button_6, 0, 1);

        // label_8
        label_8 = new Label();
        label_8.setImmediate(false);
        label_8.setWidth("-1px");
        label_8.setHeight("-1px");
        label_8.setValue(messages.getString("RenamerComponent.extension.counter"));
        gridLayout_2.addComponent(label_8, 1, 1);

        return gridLayout_2;
    }

    @AutoGenerated
    private Panel buildPanel_3() {
        // common part: create layout
        panel_3 = new Panel();
        panel_3.setCaption(messages.getString("RenamerComponent.counter"));
        panel_3.setImmediate(false);
        panel_3.setWidth("100.0%");
        panel_3.setHeight("100.0%");

        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panel_3.setContent(verticalLayout_4);

        return panel_3;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setMargin(false);

        // gridLayout_3
        gridLayout_3 = buildGridLayout_3();
        verticalLayout_4.addComponent(gridLayout_3);
        verticalLayout_4.setExpandRatio(gridLayout_3, 1.0f);

        return verticalLayout_4;
    }

    @AutoGenerated
    private GridLayout buildGridLayout_3() {
        // common part: create layout
        gridLayout_3 = new GridLayout();
        gridLayout_3.setImmediate(false);
        gridLayout_3.setWidth("100.0%");
        gridLayout_3.setHeight("100.0%");
        gridLayout_3.setMargin(true);
        gridLayout_3.setColumns(2);
        gridLayout_3.setRows(3);

        // label_9
        label_9 = new Label();
        label_9.setImmediate(false);
        label_9.setWidth("-1px");
        label_9.setHeight("-1px");
        label_9.setValue(messages.getString("RenamerComponent.counter.from"));
        gridLayout_3.addComponent(label_9, 0, 0);

        // textField_3
        textField_3 = new TextField();
        textField_3.setImmediate(false);
        textField_3.setWidth("50px");
        textField_3.setHeight("-1px");
        gridLayout_3.addComponent(textField_3, 1, 0);

        // label_10
        label_10 = new Label();
        label_10.setImmediate(false);
        label_10.setWidth("-1px");
        label_10.setHeight("-1px");
        label_10.setValue(messages.getString("RenamerComponent.counter.step"));
        gridLayout_3.addComponent(label_10, 0, 1);

        // textField_4
        textField_4 = new TextField();
        textField_4.setImmediate(false);
        textField_4.setWidth("50px");
        textField_4.setHeight("-1px");
        gridLayout_3.addComponent(textField_4, 1, 1);

        // label_11
        label_11 = new Label();
        label_11.setImmediate(false);
        label_11.setWidth("-1px");
        label_11.setHeight("-1px");
        label_11.setValue(messages.getString("RenamerComponent.counter.digits"));
        gridLayout_3.addComponent(label_11, 0, 2);

        // textField_5
        textField_5 = new TextField();
        textField_5.setImmediate(false);
        textField_5.setWidth("50px");
        textField_5.setHeight("-1px");
        gridLayout_3.addComponent(textField_5, 1, 2);

        return gridLayout_3;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_4() {
        // common part: create layout
        horizontalLayout_4 = new HorizontalLayout();
        horizontalLayout_4.setImmediate(false);
        horizontalLayout_4.setWidth("700px");
        horizontalLayout_4.setHeight("200px");
        horizontalLayout_4.setMargin(true);
        horizontalLayout_4.setSpacing(true);

        // panel_5
        panel_5 = buildPanel_5();
        horizontalLayout_4.addComponent(panel_5);
        horizontalLayout_4.setExpandRatio(panel_5, 1.0f);

        return horizontalLayout_4;
    }

    @AutoGenerated
    private Panel buildPanel_5() {
        // common part: create layout
        panel_5 = new Panel();
        panel_5.setCaption(messages.getString("RenamerComponent.example"));
        panel_5.setImmediate(false);
        panel_5.setWidth("100.0%");
        panel_5.setHeight("100.0%");

        // verticalLayout_6
        verticalLayout_6 = buildVerticalLayout_6();
        panel_5.setContent(verticalLayout_6);

        return panel_5;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_6() {
        // common part: create layout
        verticalLayout_6 = new VerticalLayout();
        verticalLayout_6.setImmediate(false);
        verticalLayout_6.setWidth("100.0%");
        verticalLayout_6.setHeight("100.0%");
        verticalLayout_6.setMargin(true);

        // table_3
        table_3 = new Table();
        table_3.setImmediate(false);
        table_3.setWidth("100.0%");
        table_3.setHeight("100.0%");
        verticalLayout_6.addComponent(table_3);
        verticalLayout_6.setExpandRatio(table_3, 1.0f);

        return verticalLayout_6;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_5() {
        // common part: create layout
        horizontalLayout_5 = new HorizontalLayout();
        horizontalLayout_5.setImmediate(false);
        horizontalLayout_5.setWidth("700px");
        horizontalLayout_5.setHeight("100px");
        horizontalLayout_5.setMargin(true);

        // panel_4
        panel_4 = buildPanel_4();
        horizontalLayout_5.addComponent(panel_4);
        horizontalLayout_5.setExpandRatio(panel_4, 1.0f);

        return horizontalLayout_5;
    }

    @AutoGenerated
    private Panel buildPanel_4() {
        // common part: create layout
        panel_4 = new Panel();
        panel_4.setImmediate(false);
        panel_4.setWidth("665px");
        panel_4.setHeight("100.0%");

        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        panel_4.setContent(verticalLayout_5);

        return panel_4;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5() {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("100.0%");
        verticalLayout_5.setHeight("100.0%");
        verticalLayout_5.setMargin(true);

        // label_12
        label_12 = new Label();
        label_12.setImmediate(false);
        label_12.setWidth("-1px");
        label_12.setHeight("-1px");
        label_12.setValue("Label");
        verticalLayout_5.addComponent(label_12);

        return verticalLayout_5;
    }

}
